stages:
  - sonar
  - build
  - deploy

variables:
  DOCKER_IMAGE: $DOCKER_USER/nodejs-app

before_script:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

code_quality:
  stage: sonar
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  script:
    - echo "docker pull $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA"
    - echo "Run container here, e.g., on a remote host"
  only:
    - main
